name: build-playground/jdunham-playground
on:
  push:
    branches:
    - main
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - run: npm run build
    - uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
      with:
        reports: "${{ github.workspace }}/**/*coverage.xml"
        targetdir: "${{ github.workspace }}/coveragereport"
        reporttypes: HtmlInline
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CoverageReport
        path: "${{ github.workspace }}/coveragereport"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CoverageReportFiles
        path: "${{ github.workspace }}/**/server.js"
