name: DeleteFiles
on: [workflow_dispatch]
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |
        ls .
        pwd
    - name: Delete files
      uses: actions/github-script@v3
      env:
        REMOVE_SOURCE_FOLDER: true
        SOURCE_FOLDER: "tests"
        FILE_PATTERNS: |-
          myFileShare
          *.js
          tests
      with:
        script: |-
          const fs = require('fs')
          const sourceFolder = process.env.SOURCE_FOLDER
          process.chdir(sourceFolder)
          const removeSourceFolder = process.env.REMOVE_SOURCE_FOLDER
          const globber = await glob.create(process.env.FILE_PATTERNS)
          const files = await globber.glob()
          console.log(process.cwd())
          files.sort().reverse()
          for (file of files) {
              console.log(`deleting ${file}`)
              await io.rmRF(file)
          }
          if (removeSourceFolder == "true" && sourceFolder !== ".") {
              if (fs.readdirSync(".").length === 0) {
                  process.chdir("${{ github.workspace }}")
                  console.log(`deleting ${sourceFolder}`)
                  console.log(process.cwd())
                  await io.rmRF(sourceFolder)
              }
          }
    - run: |-
        ls .
        pwd
