name: DeleteFiles
on: [workflow_dispatch]
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ls .
    - name: delete files
      uses: actions/github-script@v3
      env:
        FILE_PATTERNS: |
          some/file
          tests
          **.json
          **.js
          node_modules
      with:
        script: |-
          const fs = require('fs')
          
          const patterns = process.env.FILE_PATTERNS
          const globber = await glob.create(patterns.replace(/,/g, "\n"))
          const files = await globber.glob()
          files.sort(file => fs.lstatSync(file).isDirectory() ? 1 : -1)
          for (file of files) {
              console.log(`deleting ${file}`)
              await io.rmRF(file)
          }
    - run: ls .
    - run: tree
