name: DeleteFiles
on: [workflow_dispatch]
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ls .
    - name: delete files
      uses: actions/github-script@v3
      env:
        SOURCE_FOLDER: "."
        FILE_PATTERNS: |
          **/*.js
      with:
        script: |-
          const fs = require('fs').promises
          const path = require('path')
          const target = path.resolve(process.env.TARGET_LOCATION)
          process.chdir(process.env.SOURCE_FOLDER)
          const globber = await glob.create(patterns.replace(/,/g, "\n"))
          const files = await globber.glob()
          files.sort(file => fs.lstatSync(file).isDirectory() ? 1 : -1)
          for (file of files) {
            console.log(`deleting ${file}`)
            await io.rmRF(file)
          }
    - run: ls .
